### PR TITLE
Normalized Public Api Contract

### PR DESCRIPTION
**Pull request by Silvenga**
- (.Net Convention) Use correct naming conventions (PascalCase for public members, no SCREAMING_CASE, no Snake_Case).
- (.Net Convention) Vulns -> Vulnerabilities (perfer full spelling of all works on public members)
- Some `Uuid` were named `Id`, normalized all `Uuid` to favor `Id`
- Fixed the spelling of some public members.

```
IContrastRestClient.PostApplicatonSpecificMessage > IContrastRestClient.PostApplicationSpecificMessage
ContrastApplication.Stauts -> ContrastApplication.Status
```

There are two property mappings that may be incorrect:

```
    [JsonObject]
    public class TraceEventDetailResponse
    {
        [JsonProperty(PropertyName = "succes")]
        public bool Success { get; set; }
    }


    public class Server
    {
        [JsonProperty(PropertyName = "assess_sensonrs")]
        public bool AssessSensors { get; set; }
    }
```

The naming of the projects/root namespace does not follow .Net/NuGet conventions. The NuGet package is called ContrastRestClient, which should match the assembly name, which should match the root namespace (but is Contrast).

Additionally, the type `ContrastRestClient` does not follow .Net naming conventions, as the name should not match the assembly name (requires full-qualification). One of these should be renamed.

TODO
- [ ] `ContrastRestClient` type/assembly
- [ ] Enums do not match naming conventions (PascalCase)
- [ ] Possibly invalid json mappings.
- [ ] Namespaces are not conventional (should match root namespace).

### CODE REVIEW

**Comment by gmoore** [comment]
@Silvenga Checks out for me. Can you update the README with any changes that people would need to make to their code to go from 2.X to 3.0? Feel free to merge once that's in. 

About the four checkbox items you had in your description:
* If you're going to work it in your free time, go ahead
* If you might not get to it, open Jira tickets and I can backlog them to work then as I work on VS MAC.

**Review by gmoore — APPROVED** [review]
Pending README addition

**Comment by Silvenga** [comment]
@gmoore should be good for the README changes, I'll make jira tickets for the other items. Does the integrations team own this package?

**Comment by gmoore** [comment]
@Silvenga We're the de facto owners, yes. Thanks for the README change. I'll try to get this in asap.

**Comment by gmoore** [comment]
Going to merge this next week after we release VS MAC.

**Comment by Silvenga** [comment]
@gmoore so do we want these other breaking changes in before that release?

**Comment by gmoore** [comment]
Good point. I was worried about breaking our plugin set to go out on Monday but I tested it and looks like we're good to go.

**Pull request merged**
